DROP TABLE IF EXISTS steps CASCADE;
DROP TABLE IF EXISTS levels CASCADE;

CREATE TABLE levels (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT
);

CREATE TABLE steps (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  level_id INTEGER REFERENCES levels(id) ON DELETE CASCADE
);

